#!/bin/sh

#
# Test boolean operator precedence
#

cat >"$CONFIG" <<EOF
true && true || false || false && false -> info("&& and || logic works")
true && (true || (false || false)) && false -> info("Should not print")

true == true && false -> info("Should not print")
(true == false) || false -> info("Parentheses precedence takes over logical operators: shouldn't print")

1 -> info("1 is true")
"1" -> info("'1' is true")
0 -> info("0 is not true so this shouldn't print")
"0" -> info("'0' is not true so this shouldn't print")
"true" -> info("'true' is true")
"false" -> info("'false' is not true so this shouldn't print")

my_true=1
my_false=0

my_true && my_false -> info("true && false == false")
my_true && my_true -> info("true && true == true")
!my_true && my_true -> info("!true && true == false")
!my_true && my_false -> info("!true && false == false")
my_true && !my_false -> info("true && !false == true")
!my_false && my_true -> info("!false && true == true")
!my_false && my_false -> info("!false && false == false")

my_true || my_false -> info("true || false == true")
my_true || my_true -> info("true || true == true")
!my_true || my_true -> info("!true || true == true")
!my_true || my_false -> info("!true || false == false")
my_true || !my_false -> info("true || !false == true")
!my_false || my_true -> info("!false || true == true")
!my_false || my_false -> info("!false || false == true")

EOF


cat >"$EXPECTED" <<EOF
fixture: mkdir("/mnt", 777)
fixture: mkdir("/dev", 777)
fixture: mkdir("/sys", 777)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 10, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
&& and || logic works
1 is true
'1' is true
'true' is true
true && true == true
true && !false == true
!false && true == true
true || false == true
true || true == true
!true || true == true
true || !false == true
!false || true == true
!false || false == true
fixture: mount("/dev/mmcblk0p2", "/mnt", "squashfs", 1, data)
fixture: mount("/dev", "/mnt/dev", "(null)", 8192, data)
fixture: umount("/sys")
fixture: unlink("/init")
fixture: unlink("/nerves_initramfs.cfg")
fixture: rmdir("/root")
fixture: rmdir("/sys")
fixture: mount(".", "/", "(null)", 8192, data)
fixture: chroot(.)
Hello from the chained /sbin/init
EOF
