#!/bin/sh

#
# Test boolean operator precedence
#

cat >"$CONFIG" <<EOF
true && true || false || false && false -> info("&& and || logic works")
true && (true || (false || false)) && false -> info("Should not print")

true == true && false -> info("Should not print")
(true == false) || false -> info("Paren precedence takes over logical operators: shouldn't print")
EOF


cat >"$EXPECTED" <<EOF
fixture: mkdir("/mnt", 777)
fixture: mkdir("/dev", 777)
fixture: mkdir("/sys", 777)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 10, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
&& and || logic works
fixture: mount("/dev/mmcblk0p2", "/mnt", "squashfs", 1, data)
fixture: mount("/dev", "/mnt/dev", "(null)", 8192, data)
fixture: umount("/sys")
fixture: unlink("/init")
fixture: unlink("/nerves_initramfs.cfg")
fixture: rmdir("/root")
fixture: rmdir("/sys")
fixture: mount(".", "/", "(null)", 8192, data)
fixture: chroot(.)
Hello from the chained /sbin/init
EOF
