#!/bin/sh

#
# Test boolean operator precedence
#

cat >"$CONFIG" <<EOF
true && true || false || false && false -> print("&& and || logic works")
true && (true || (false || false)) && false -> print("Should not print")

true == true && false -> print("Should not print")
(true == false) || false -> print("Parentheses precedence takes over logical operators: shouldn't print")

1 -> print("1 is true")
"1" -> print("'1' is true")
0 -> print("0 is not true so this shouldn't print")
"0" -> print("'0' is not true so this shouldn't print")
"true" -> print("'true' is true")
"false" -> print("'false' is not true so this shouldn't print")

my_true=1
my_false=0

my_true && my_false -> print("true && false == false")
my_true && my_true -> print("true && true == true")
!my_true && my_true -> print("!true && true == false")
!my_true && my_false -> print("!true && false == false")
my_true && !my_false -> print("true && !false == true")
!my_false && my_true -> print("!false && true == true")
!my_false && my_false -> print("!false && false == false")

my_true || my_false -> print("true || false == true")
my_true || my_true -> print("true || true == true")
!my_true || my_true -> print("!true || true == true")
!my_true || my_false -> print("!true || false == false")
my_true || !my_false -> print("true || !false == true")
!my_false || my_true -> print("!false || true == true")
!my_false || my_false -> print("!false || false == true")

EOF


cat >"$EXPECTED" <<EOF
fixture: mkdir("/mnt", 755)
fixture: mkdir("/dev", 755)
fixture: mkdir("/sys", 555)
fixture: mkdir("/proc", 555)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 10, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mount("proc", "/proc", "proc", 14, data)
&& and || logic works
1 is true
'1' is true
'true' is true
true && true == true
true && !false == true
!false && true == true
true || false == true
true || true == true
!true || true == true
true || !false == true
!false || true == true
!false || false == true
fixture: mount("/dev/mmcblk0p2", "/mnt", "squashfs", 1, data)
fixture: symlink("/dev/mmcblk0","/dev/rootdisk0")
fixture: symlink("/dev/mmcblk0p6","/dev/rootdisk0p6")
fixture: symlink("/dev/mmcblk0p5","/dev/rootdisk0p5")
fixture: symlink("/dev/mmcblk0p2","/dev/rootdisk0p2")
fixture: symlink("/dev/mmcblk0p1","/dev/rootdisk0p1")
fixture: mount("/dev", "/mnt/dev", "(null)", 8192, data)
fixture: umount("/sys")
fixture: umount("/proc")
fixture: unlinkat("bin", AT_REMOVEDIR)
fixture: unlinkat("usr", AT_REMOVEDIR)
fixture: rmdir("/sys")
fixture: rmdir("/proc")
fixture: mount(".", "/", "(null)", 8192, data)
fixture: chroot(.)
Hello from the chained /sbin/init
EOF
