#!/bin/sh

#
# Specify a GPT partition by UUID
#

cat >"$CONFIG" <<EOF
rootfs.path="PARTUUID=7e7b6f06-8aaf-42c6-9c3b-6ede014885a6"
EOF

cat >"$EXPECTED" <<EOF
fixture: mkdir("/mnt", 755)
fixture: mkdir("/dev", 755)
fixture: mkdir("/sys", 555)
fixture: mkdir("/proc", 555)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 10, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mount("proc", "/proc", "proc", 14, data)
fixture: mount("/dev/mmcblk0p5", "/mnt", "squashfs", 1, data)
fixture: mount("/dev", "/mnt/dev", "(null)", 8192, data)
fixture: umount("/sys")
fixture: umount("/proc")
fixture: unlinkat("bin", AT_REMOVEDIR)
fixture: unlinkat("usr", AT_REMOVEDIR)
fixture: rmdir("/sys")
fixture: rmdir("/proc")
fixture: mount(".", "/", "(null)", 8192, data)
fixture: chroot(.)
Hello from the chained /sbin/init
EOF

