#!/bin/sh

#
# Specify a MBR partition by UUID
#

cat >$CONFIG <<EOF
rootfs.path="PARTUUID=3fc3e2d4-02"
EOF

cat >$EXPECTED <<EOF
fixture: mount("devtmpfs", "/dev", "devtmpfs", 10, data)
fixture: mkdir("/mnt", 777)
fixture: mount("/dev/sda2", "/mnt", "squashfs", 1, data)
fixture: unlink("/init")
fixture: rmdir("/root")
fixture: mount("/dev", "/mnt/dev", "(null)", 8192, data)
fixture: mount(".", "/", "(null)", 8192, data)
fixture: chroot(.)
Hello from the chained /sbin/init
EOF

