#!/bin/sh

#
# Test that ls works
#

cat >"$CONFIG" <<EOF
info("ls with no arguments")
ls()
info("ls /usr")
ls("/usr")
EOF

cat >"$EXPECTED" <<EOF
fixture: mkdir("/mnt", 755)
fixture: mkdir("/dev", 755)
fixture: mkdir("/sys", 555)
fixture: mkdir("/proc", 555)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 10, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mount("proc", "/proc", "proc", 14, data)
ls with no arguments 
.                               <DIR>
..                              <DIR>
dev                             <DIR>
init                            
mnt                             <DIR>
nerves_initramfs.conf           
proc                            <DIR>
sys                             <DIR>
usr                             <DIR>
ls /usr 
.                               <DIR>
..                              <DIR>
bin                             <DIR>
fixture: mount("/dev/mmcblk0p2", "/mnt", "squashfs", 1, data)
fixture: mount("/dev", "/mnt/dev", "(null)", 8192, data)
fixture: umount("/sys")
fixture: umount("/proc")
fixture: unlinkat("bin", AT_REMOVEDIR)
fixture: unlinkat("usr", AT_REMOVEDIR)
fixture: rmdir("/sys")
fixture: rmdir("/proc")
fixture: mount(".", "/", "(null)", 8192, data)
fixture: chroot(.)
Hello from the chained /sbin/init
EOF

