#!/bin/sh

#
# Test that cmd can run a program
#

cat >"$CONFIG" <<EOF
fwup_revert()
EOF

cat >"$EXPECTED" <<EOF
fixture: mkdir("/mnt", 755)
fixture: mkdir("/dev", 755)
fixture: mkdir("/sys", 555)
fixture: mkdir("/proc", 555)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 10, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mount("proc", "/proc", "proc", 14, data)
Hello from fwup: revert.fw -d /dev/mmcblk0 -t revert
fixture: reboot(0x01234567)
EOF

