#!/bin/sh

#
# Test that poweroff works
#

cat >"$CONFIG" <<EOF
poweroff()
info("Does not print")
EOF

cat >"$EXPECTED" <<EOF
fixture: mkdir("/mnt", 777)
fixture: mkdir("/dev", 777)
fixture: mkdir("/sys", 777)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 10, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: reboot(0x4321fedc)
EOF

